const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getFilters: () => ipcRenderer.invoke('get-filters'),
  saveFilters: (filters) => ipcRenderer.send('save-filters', filters),
  resetFilters: () => ipcRenderer.send('reset-filters'),
  closeWindow: () => ipcRenderer.send('close-window'),
  openExternal: (url) => ipcRenderer.send('open-external-link', url),
  getAdSkipperSettings: () => ipcRenderer.invoke('get-ad-skipper-settings'),
  saveAdSkipperSettings: (settings) => ipcRenderer.send('save-ad-skipper-settings', settings),
  getAdblockStats: () => ipcRenderer.invoke('get-adblock-stats'),
  resetAdblockStats: () => ipcRenderer.send('reset-adblock-stats'),
  getTranslations: () => ipcRenderer.invoke('get-translations', [
      'ad_filter_config_title',
      'enabled',
      'filter_name',
      'filter_url',
      'add_new_filter',
      'more_filters',
      'save',
      'cancel',
      'delete',
      'reset',
      'filter_list',
      'adblock_status',
      'reset_counters',
      'status_state',
      'status_enabled_lists',
      'status_checked',
      'status_blocked',
      'simple_skipper',
      'simple_skipper_desc',
      'adblock_active',
      'adblock_inactive',
      'adblock_no_lists',
      'adblock_not_active',
      'adblock_waiting',
      'adblock_nothing_blocked',
      'adblock_blocking',
      'error_filter_name_empty',
      'error_filter_url_invalid'
  ])
});